# Generated by Django 2.2 on 2019-05-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='trained_model',
            field=models.FileField(upload_to='trained_models/'),
        ),
    ]
