# Generated by Django 2.2 on 2019-05-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_auto_20190528_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='trained_model',
            field=models.FileField(blank=True, null=True, upload_to='trained_models/'),
        ),
    ]
