# Generated by Django 2.2 on 2019-05-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_predict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='method',
            field=models.CharField(choices=[('SVC', 'SVC - classification'), ('KNN', 'KNN - classification')], max_length=50),
        ),
    ]
