# Generated by Django 2.2 on 2019-05-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0005_auto_20190529_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='predications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
